%% 参数设置
f_max=4e-7*fc;
fs=1e7;                    %定义调制信号的采样率
Flat = doppler('Flat');
Jakes=doppler('Jakes');
GaussI=doppler('BiGaussian','PowerGains',[5 1],'NormalizedCenterFrequencies',[-0.8 0.4],'NormalizedStandardDeviations',[0.05 0.1]);
GaussII=doppler('BiGaussian','PowerGains',[20*sqrt(10)/3 1],'NormalizedCenterFrequencies',[0.7 -0.4],'NormalizedStandardDeviations',[0.1 0.15]);
%% 瑞利衰落信道建立
rchannel = comm.RayleighChannel( ...
    'SampleRate',fs, ...
    'PathDelays',[0 0.2e-6 0.5e-6 1.6e-6 2.3e-6 5e-6], ...
    'AveragePathGains',[-3 0 -2 -6 -8 -10], ...
    'NormalizePathGains',true, ...
    'MaximumDopplerShift',f_max, ...
    'DopplerSpectrum',{Jakes, Jakes, Jakes, GaussI, GaussII, GaussII}, ...
    'RandomStream','mt19937ar with seed', ...
    'Visualization','Off',...
    'Seed',22, ...
    'PathGainsOutputPort',true);