clc
clear all
close all
%参数设置
fc = 20e3;
SubCarryN=128;                   %子载波数
SubCarry_eff=SubCarryN*1/4;      %有效子载波数
ratio=1/4;                %CP length ratio
fftLen=SubCarryN;         %FFT length
SymbN=10000;             %number of OFDM symbols
GuardLen=SubCarryN*ratio;    %CP length
SymLen=SubCarryN+GuardLen;  %length of each symbol after cp
beta=1/32; %rolloff ratio
SNR_dB=0:10;             %信噪比取值，以db为单位
% SNR_dB=5;%设置信噪比db
%%----------------------------------------发射端-----------------------------------------------------%%
%输入比特序列长度=子载波数×符号数×每符号比特数
% for index=1:length(SNR)
% for p=1:200
SignalLen=SubCarry_eff*SymbN;
M=4;                                  %调制阶数
Signal=randi([0 M-1],1,SignalLen);
if M==4
    Signal=pskmod(Signal,M,pi/4);%
else
    Signal=qammod(Signal,M);
end
ParaSymSig=reshape(Signal,SubCarry_eff,SymbN);
% plot(ParaSymSig,'*r');
%在中间补零
% x=[ParaSymSig(1:SubCarryN*3/8,1:SymbN);zeros(SubCarryN/4,SymbN);ParaSymSig(SubCarryN*3/8+1:SubCarry_eff,1:SymbN)];%有效子载波占3/4
x=[ParaSymSig(1:SubCarryN*1/8,1:SymbN);zeros(SubCarryN*3/4,SymbN);ParaSymSig(SubCarryN*1/8+1:SubCarry_eff,1:SymbN)];%有效子载波占1/4
y=ifft(x,fftLen,1);   %通过傅里叶反变换，将频域数据转化为时域数据，1024行，500列

%在数组中加循环前缀的方法
y_CP=[y(fftLen-GuardLen+1:fftLen,:);y]; %加入循环前缀

%rcosfilter window 
window_coff=rcoswindow(beta,SymLen);
y_window=zeros(SymLen,SymbN);
for n=1:SymbN
    y_window(:,n)=y_CP(:,n).*window_coff.';
end
% y_window=y_CP;
%并串变换
TrData=reshape(y_window,1,SymLen*SymbN);%并串变换，转换成一串，变成一行，7680列
%瑞丽信道参数设置
%%Rayleigh channel generated by using randn
P_hdB=[0,-17,-18,-30];%各信道的功率特征
% P_hdB=[0,0,0,0];%各信道的功率特征
D_h=[0,30,60,200];%各信道的延迟（采样点）
P_h=10.^(P_hdB/10);%各信道的功率特性
NH=length(P_hdB);%多径信道的个数
LH=D_h(end)+1;%信道长度（延迟过后）
for N=1:length(SNR_dB)
%% The channel varies among different symbols
% rece_signal=zeros(SubCarryN,SymbN);
A_h=(randn(1,NH)+sqrt(-1)*randn(1,NH)).*sqrt(P_h/2);%瑞丽随机变量
h=zeros(1,LH);%初始化信道冲击响应模型
h(D_h+1)=A_h;%信道冲击响应（同时体现出衰减系数和信道时延）
%rx_channel = y_window;
rx_channel=conv(TrData,h.','full');%卷积，输出通过该信道的信号
ReData=awgn(rx_channel,SNR_dB(N),'measured');%瑞丽信道
r1=ReData(1:SymbN*SymLen);           %接收数据（可以选取一部分）
%去循环前缀
r1 = reshape(r1, SymLen, SymbN);
rev_signal=r1(GuardLen+1:SymLen,:);%去掉循环前缀并恢复格式
rece_signal=fft(rev_signal);

%尝试多个符号累加
F1=zeros(1,SubCarryN);%F1是识别空载波的特征量
%识别空载波
F1countLen=SymbN;
for i=1:SubCarryN
    [cumulants11]=func_get_cumulants(rece_signal(i,:));
    F1(i)=cumulants11(7);%=C21, the power of each subcarrier
%     F1(i)=cumulants11(8);%=C42/((C21)^2)
end
%画出F1的分布
% figure;
% i=1:SubCarryN;
% plot(i,F1);hold on;
%%
% % 通过识别出的空载波求N
% %矩阵，用来存F1的数值
F1_B=0.1*max(F1);%门限
[F1v,F1index]=find(F1<F1_B);
EmptySub_Num=length(F1index);  %Number of empty subcarries
NoEmptySub_Num=SubCarryN-EmptySub_Num; %Number of non-empty subcarries

EmptySub=rece_signal(F1index,:); %store received empty subcarries
NoEmptySub=rece_signal(setdiff([1:SubCarryN],F1index),:);%store received non-empty subcarries

noise_part=sum(sum(abs(EmptySub).^2));%energy of noise
all=sum(sum(abs(rece_signal).^2));%power of sum
signal_part=sum(sum(abs(NoEmptySub).^2));%power of sub

noise = noise_part * (SubCarryN/(SubCarryN - SubCarry_eff));
signal = signal_part - noise_part * (SubCarry_eff/(SubCarryN - SubCarry_eff));

snr=signal/noise;
SNR_est=10*log10(snr)
end